// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Hu_3Ou9whSNpkCAeQx_M30xB9ozI3gU',
    appId: '1:1046380242656:web:f7bf63f5e0fd57aa8f5285',
    messagingSenderId: '1046380242656',
    projectId: 'flash-chat-f2256',
    authDomain: 'flash-chat-f2256.firebaseapp.com',
    storageBucket: 'flash-chat-f2256.appspot.com',
    measurementId: 'G-J4TRM425ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJosgpiswsNwE5elaD15AuKjPK_VTatNQ',
    appId: '1:1046380242656:android:897de5d479355dc58f5285',
    messagingSenderId: '1046380242656',
    projectId: 'flash-chat-f2256',
    storageBucket: 'flash-chat-f2256.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG2lKFt1lXkb9ZpfJqE-oECYz17nZ3sEs',
    appId: '1:1046380242656:ios:4b9bca530af49cad8f5285',
    messagingSenderId: '1046380242656',
    projectId: 'flash-chat-f2256',
    storageBucket: 'flash-chat-f2256.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG2lKFt1lXkb9ZpfJqE-oECYz17nZ3sEs',
    appId: '1:1046380242656:ios:4b9bca530af49cad8f5285',
    messagingSenderId: '1046380242656',
    projectId: 'flash-chat-f2256',
    storageBucket: 'flash-chat-f2256.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );
}
